- id: circleci-validate
  name: CircleCI config validation
  description: Validate CircleCI config yaml
  entry: pre_commit_hooks/circleci-validate.sh
  language: script
  files: ^.circleci/config.yml$
